export const TRANSACTION_ACTION_TYPES = {
    SET_LIST: 'SET_LIST',
    SET_TRANSACTION_INCOME_COUNTER: 'SET_TRANSACTION_INCOME_COUNTER',
    SET_TRANSACTION_OUTCOME_COUNTER: 'SET_TRANSACTION_OUTCOME_COUNTER',
    SET_TRANSACTION_INCOME_TOTAL: 'SET_TRANSACTION_INCOME_TOTAL',
    SET_TRANSACTION_OUTCOME_TOTAL: 'SET_TRANSACTION_OUTCOME_TOTAL'
};